### ISSUE TITLE
extra column

### ISSUE THREAD

**Issue by Himanivaidya** [TheJacksonLaboratory/epihet#1]
Hello,

 I have noticed that methclone output generates an extra column that is empty (column number 47 when analyzing two files). right now trying to use epihet and looks withe the codes published for trial run:

files = c(system.file("extdata","D-2238.chr22.region.methClone_out.gz",package = "epihet"),
system.file("extdata","D-2668.chr22.region.methClone_out.gz",package = "epihet"),
system.file("extdata","N-1.chr22.region.methClone_out.gz",package = "epihet"),
system.file("extdata","N-2.chr22.region.methClone_out.gz",package = "epihet"))

ids = epihet::splitn(basename(files),"[.]",1)

GR.List = epihet::makeGR(files = files, ids = ids,
cores = 1, sve = FALSE)

and I  get the following error:

Error in { : task 1 failed - "Item 1 of j is 27 which is outside the column number range [1,ncol=0]"

is this the same extra column being generated?

**Comment by jaroslavj** [comment]
Got the same error :)
> files = c(system.file("extdata","D-2238.chr22.region.methClone_out.gz",package = "epihet"),
           system.file("extdata","D-2668.chr22.region.methClone_out.gz",package = "epihet"),
           system.file("extdata","N-1.chr22.region.methClone_out.gz",package = "epihet"),
           system.file("extdata","N-2.chr22.region.methClone_out.gz",package = "epihet"))
> ids = epihet::splitn(basename(files),"[.]",1)
> GR.List = epihet::makeGR(files = files, ids = ids,
                          cores = 1, sve = FALSE)
Error in { : 
  task 1 failed - "Item 1 of j is 27 which is outside the column number range [1,ncol=0]"
> ls()
[1] "files" "ids"  
> summary(files)
   Length     Class      Mode 
        4 character character 
> files
[1] "E:/Documents/R/win-library/3.6/epihet/extdata/D-2238.chr22.region.methClone_out.gz"
[2] "E:/Documents/R/win-library/3.6/epihet/extdata/D-2668.chr22.region.methClone_out.gz"
[3] "E:/Documents/R/win-library/3.6/epihet/extdata/N-1.chr22.region.methClone_out.gz"   
[4] "E:/Documents/R/win-library/3.6/epihet/extdata/N-2.chr22.region.methClone_out.gz"   
> ids
[1] "D-2238" "D-2668" "N-1"    "N-2"   
> GR.List = epihet::makeGR(files = files, ids = ids,
                           sve = FALSE)
Error in { : 
  task 1 failed - "Item 1 of j is 27 which is outside the column number range [1,ncol=0]"

**Comment by xiaowenchenjax** [comment]
it worked very well in linux. please make sure you install epihet 1.2.0
