### ISSUE TITLE
compMatrix bug

### ISSUE THREAD

**Issue by alexyfyf** [TheJacksonLaboratory/epihet#4]
When I set p=1 in compMatrix, I can still find NA values in the result.
I investigated the data, and found that the epialleles with NA had two lines in some of the input files, which is on the + and - strand, but the same locus.
```
GRanges object with 2 ranges and 6 metadata columns:
      seqnames            ranges strand |                         values.loci values.read1
         <Rle>         <IRanges>  <Rle> |                         <character>    <integer>
  [1]       10 60831242-60831253      + | 60831242:60831245:60831250:60831253          208
  [2]       10 60831242-60831253      - | 60831242:60831245:60831250:60831253          232
      values.meth1 values.pdr    values.epipoly    values.shannon
         <numeric>  <numeric>         <numeric>         <numeric>
  [1]      3.72596  0.1346155  0.24343497699689 0.541693227822759
  [2]      4.09483 0.11206888 0.208308627728889 0.519880586846933
  -------
  seqinfo: 25 sequences from an unspecified genome; no seqlengths
```

I noticed in the code, the table count of loci was used, and strand information should be added.

**Comment by xiaowenchenjax** [comment]
what data you show here? your data or the example data in R package?

**Comment by alexyfyf** [comment]
> what data you show here? your data or the example data in R package?

Sorry, I should have closed the issue. 
It is actually a methclone bug. Because I realized I should not see two CpGs same location but in opposite strands. 
But it might still be worthy to add strand information when you generate the `location` column in `compMatrix` function. 

Something like this:
```r
 location
1     1_-_10038037:10038042:10038047:10038066
2     1_-_10040244:10040249:10040262:10040279
```

Thank you.
